spring.application.name=user-service
server.port=8081

# DB Connections
spring.datasource.url=jdbc:posgresql://localhost:5000/ice-skate-db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# Flyway Migrations
spring.flyway.locations=classpath:db/migration
